version: '3'

services:
  app:
    build: .
    container_name: stock_app
    image: stock_app
    ports:
      - 5000:5000
    command: >
      sh -c "
        pipenv run python3 -m flask run --host=0.0.0.0
      "
    volumes:
      - .:/app
